const dummyPosts = [
  {
    id: 1,
    createdAt: "2022-06-26T03:34:54.7318127+07:00",
    idUser: 1,
    idUserUniversitas: 1,
    user: {
      id: 1,
      name: "Universitas Terbuka",
      profilePic: "",
    },
    materi: "https://source.unsplash.com/random/500x500",
    caption: "lorem ipsum dolor is amet",
    isNews: false,
    isSaved: false,
    isLiked: false,
    jumlahLike: 0,
    jumlahComment: 0,
  },
  {
    id: 2,
    createdAt: "2022-06-26T03:35:10.1440718+07:00",
    idUser: 1,
    idUserUniversitas: 1,
    user: {
      id: 1,
      name: "Universitas Terbuka",
      profilePic: "",
    },
    materi: "https://source.unsplash.com/random/500x500",
    caption: "lorem ipsum dolor is amet lorem ipsum amet is dolor",
    isNews: false,
    isSaved: false,
    isLiked: false,
    jumlahLike: 0,
    jumlahComment: 0,
  },
  {
    id: 3,
    createdAt: "2022-06-26T03:35:26.2241596+07:00",
    idUser: 3,
    idUserUniversitas: 1,
    user: {
      id: 3,
      name: "Badan Eksekutif Mahasiswa UT",
      profilePic: "",
    },
    materi: "https://source.unsplash.com/random/500x500",
    caption:
      "lorem ipsum dolor is amet lorem ipsum amet is dolor asf adfasdfasdf ",
    isNews: false,
    isSaved: false,
    isLiked: false,
    jumlahLike: 0,
    jumlahComment: 0,
  },
];
